name: property_map
version: 0.0.13
author: Daniel Rodriguez <seth.illgard@gmail.com>
description: "PropertyMap allows you to quickly implement property bags in dart. It\
  \ consists of 2 main classes: PropertyMap and PropertyList.\r\nPropertyMap is a\
  \ wrapper around Map<String, dynamic>. PropertyList is a wrapper around List<dynamic>.\r\
  \nThe benefit of using them is that they can restrict the data that is added to\
  \ them so it is possible to guarantee serialization, and they convert children Maps\
  \ and Lists recursively to propertyMaps and PropertyLists.\r\nBy default, they can\
  \ only take simple objects (as defined in dart:json) and Serializable objects. The\
  \ configuration object passed to the constructor allows you to modify this behavior\
  \ if needed."
homepage: https://github.com/sethillgard/property_map
dependencies:
  unittest: any
